@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User #red
box Application
    participant "Spring Security" #orange
    participant "Spring Framework\nDispatcherServlet" #99FF99
end box

User -> "Spring Security": GET <b>http://localhost:8189/hello.html
activate "Spring Security"
"Spring Security" -> "Spring Security": Пользователь не\nаутентифицирован
"Spring Security" --> User: <b>401 Unauthorized\nWWW-Authenticate: Basic Realm="my realm"
deactivate "Spring Security"
User -> "Spring Security"++: <b>GET http://localhost:8189/hello.html\nAuthorization Basic ...
"Spring Security" -> "Spring Security": Аутентификация\nпользователя
"Spring Security" -> "Spring Framework\nDispatcherServlet"++: <b>GET http://localhost:8189/hello.html\nAuthorization Basic ...
"Spring Framework\nDispatcherServlet" --> "Spring Security"--: <b>200 OK\nContent-type: text/html\n\n<h1>Hello</h1>
"Spring Security" --> User--: <b>200 OK\nContent-type: text/html\n\n<h1>Hello</h1>

'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response
@enduml